# Generated by Django 5.0.2 on 2024-02-23 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Wire Transfer/EFT', 'Wire Transfer/EFT'), ('Cash on Delivery', 'Cash on Delivery')], max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('process_ID', models.CharField(blank=True, max_length=255)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
