# Generated by Django 4.2.10 on 2024-03-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_business',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_member',
            field=models.BooleanField(default=True),
        ),
    ]
